1)  Classic Model

In [1]:
# Imports go here
import torch
import numpy as np
import tqdm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd
from dataloader import CustomDataloader
import torch.nn as nn
from networks import CustomCNN

In [2]:
# Load data
data_dict = torch.load('data/ages_processed.pt')

# Instantiate dataloaders
train_dataloader = CustomDataloader(data_dict['x_train'], data_dict['y_train'], batch_size=12, buffer_size=36)
val_dataloader = CustomDataloader(data_dict['x_val'], data_dict['y_val'], batch_size=12, buffer_size=36)
test_dataloader = CustomDataloader(data_dict['x_test'], data_dict['y_test'], batch_size=12, buffer_size=36)

# Convert the data to numpy arrays if needed
x_train_np = train_dataloader.x.numpy()
y_train_np = train_dataloader.y.numpy()

# Ensure that y_train_np is a 1D array
y_train_np = y_train_np.ravel()

# Instantiate and train the logistic regression model
model = LogisticRegression(max_iter=10000)
model.fit(x_train_np, y_train_np)

# Predict on the validation set
val_preds = model.predict(val_dataloader.x.numpy())

# Compute the confusion matrix and accuracy on the validation set
mat = confusion_matrix(val_dataloader.y.numpy(), val_preds)
accuracy = np.trace(mat) / np.sum(mat)
print(mat)
print(f'Accuracy on the validation set: {accuracy}')

[[205   0   0 ...   0   0   0]
 [ 99   0   0 ...   0   0   0]
 [ 39   3   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
Accuracy on the validation set: 0.1887389287220582


2. Neutral Network

Now we'll attempt to train a model only on images, (this was a fail)

In [4]:
# instantiate dataloaders
input = 'data/dataset.pt'

train_dataloader = CustomDataloader(data_dict['x_train'], data_dict['y_train'], batch_size=12, buffer_size=36)
val_dataloader = CustomDataloader(data_dict['x_val'], data_dict['y_val'], batch_size=12, buffer_size=36)
test_dataloader = CustomDataloader(data_dict['x_test'], data_dict['y_test'], batch_size=12, buffer_size=36)

In [6]:
# code taken from https://www.hackersrealm.net/post/gender-and-age-prediction-using-python, changes reverted to original

model = CustomCNN()

inputs = Input((input_shape))
# convolutional layers
conv_1 = Conv2D(32, kernel_size=(3, 3), activation='relu') (inputs)
maxp_1 = MaxPooling2D(pool_size=(2, 2)) (conv_1)
conv_2 = Conv2D(64, kernel_size=(3, 3), activation='relu') (maxp_1)
maxp_2 = MaxPooling2D(pool_size=(2, 2)) (conv_2)
conv_3 = Conv2D(128, kernel_size=(3, 3), activation='relu') (maxp_2)
maxp_3 = MaxPooling2D(pool_size=(2, 2)) (conv_3)
conv_4 = Conv2D(256, kernel_size=(3, 3), activation='relu') (maxp_3)
maxp_4 = MaxPooling2D(pool_size=(2, 2)) (conv_4)

flatten = Flatten() (maxp_4)

# fully connected layers
dense_1 = Dense(256, activation='relu') (flatten)

dropout_1 = Dropout(0.3) (dense_1)

output_1 = Dense(1, activation='relu', name='age_out') (dropout_1)

model = Model(inputs=[inputs], outputs=[output_1, output_2])

model.compile(loss=['binary_crossentropy', 'mae'], optimizer='adam', metrics=['accuracy'])

NameError: name 'Input' is not defined